title: Anirban Pal
logo: # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  GitHub portfolio to showcase my analytics and data science related work. 
  <br><br>
  <a href="https://www.linkedin.com/in/anirban-pal"><img src="images/linkedin.png" data-canonical-src="images/linkedin.png" width="75" height="75" /></a>
